# Seção 2 - Deep Learning and Tensorflow Fundamentals

## Definições

- **Deep Learning**: é uma sub-área de Machine Learning que envolve o aprendizado profundo de máquina, em que algoritmos buscam padrões em fontes de dados desestruturados, como textos, imagens, áudios. A modelagem acontece pelas redes neurais, que são estruturas que recebem, processam e constroem os modelos a partir dos dados, além de corrigir os erros e otimizar os parâmetros para aumentar a acurácia desses modelos. Assim, o Deep Learning atua como uma arquitetura de processamento e modelagem de dados não-estruturados, de forma automatizada a partir dos dados de input, resultando em previsões do objeto real em questão.

- **Redes Neurais**: As redes neurais são estruturas de processamento de dados que formam a arquitetura do Deep Learning. Como disse logo acima, elas buscam imitar o processo da cognição humana ao conectar diversas camadas de neurônios artificiais.Esses neurônios atuam combinando os dados recebidos, atribuindo-lhes pesos e vieses e associando-os a funções específicas de custo e ativação. Dessa forma, esses elementos trabalham juntos para definir as etapas de processamento até o output, que deve reconhecer, classificar ou descrever objetos reais a partir dos dados.

No Machine Learning, temos dados que são, na maioria das vezes, estruturados, e o procedimento de treinamento de um modelo com regras que encontramos ao manipular e processar os dados, além de haver um valor-alvo para basearmos a resposta do modelo em cada exemplo. No Deep Learning, temos apenas um input e um output esperado, e deixamos que as redes neurais processem os dados, encontrem alguma forma de estruturá-los e busquem por padrões que possam ajudar a chegar no resultado do output que esperamos.

Para um problema complexo, como ensinar um carro a dirigir sozinho, que possui um volume muito grande de dados, o Deep Learning pode ser a alternativa mais viável. Uma vez que estamos lidando com dados desestruturados e em grande volume, a estrutura de redes neurais traz uma capacidade de lidar de maneira mais eficiente com uma variedade de parâmetros e filtrá-los de acordo com sua relevância em cada camada.

**O Deep Learning é indicado para as seguintes situações:**

- Problemas com longas listas de regras
- Ambientes que mudam constantemente, i.e, Adaptação a novos cenários
- Descobrir insights em grandes quantidades de dados

**Deep Learning não é indicado nas seguintes situações:**

- Quando necessitamos interpretabilidade: os padrões de DL normalme}nte não são interpretáveis por humanos
- Quando a abordagem tradicional é melhor, isto é, com um sistema de regras simples
- Quando erros são inaceitáveis, pois outputs no DL podem ser imprevisíveis 
- Quando não há muitos dados disponíveis, pois modelos de DL necessitam de grandes quantidade de dados para manter uma boa performance


### Tensorflow

Tensorflow é uma biblioteca de Machine Learning end-to-end. Nela, é possível escrever códigos de DL em Python e rodá-los utilizando GPU (Graphics Processing Units) ou TPU (Tensor Processing Units). O Tensorflow permite o pré-processamento dos dados, modelagem e deploy de aplicações, além de oferecer um hub de modelos já construídos de DL.

In [3]:
import tensorflow as tf
import numpy as np

In [4]:
print(f'Versão do Tensorflow: {tf.__version__}')

Versão do Tensorflow: 2.15.0


#### tf.constant()

In [5]:
# Criar tensores com tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

Criamos um tensor constante de ordem zero, ou seja, um escalar. O escalar é simplesmente a representação de um número. Se checarmos o número de dimensões desse tensor escalar, resultará em:

In [6]:
print(f'Número de dimensões: {scalar.ndim}')

Número de dimensões: 0


In [7]:
vector = tf.constant([7, 2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 2])>

Note que, para criar um vetor, passamos uma lista de números para a função `tf.constant()`. Vamos checar as dimensões do vetor:

In [8]:
print(f'Número de dimensões: {vector.ndim}')

Número de dimensões: 1


Como era de se esperar, o vetor já é um tensor de grau 1, contendo portanto uma dimensão. Se aumentarmos a dimensão, teremos uma matriz.

In [9]:
matrix = tf.constant([[5, 2],
                     [3, 6]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 2],
       [3, 6]])>

In [10]:
print(f'Número de dimensões: {matrix.ndim}')

Número de dimensões: 2


In [11]:
# Especificando o tipo dos dados no tensor
matrix_2 = tf.constant([[3., 5., 1.],
                        [5., 12., 43.],
                        [2., 5., 8.]], dtype = tf.float16)
matrix_2

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[ 3.,  5.,  1.],
       [ 5., 12., 43.],
       [ 2.,  5.,  8.]], dtype=float16)>

Manipular os tipos dos dados é útil, pois pode economizar espaço de armazenamento das variáveis nas unidades de processamento, tornando os processos mais rápidos. Para número que não carregam tanta precisão, podemos utilizar um tipo de dados que ocupa menos espaço.

Note que essa matriz possui um formato diferente da primeira, contudo o número de dimensões continua o mesmo.

In [12]:
print(f'Número de dimensões: {matrix_2.ndim}')

Número de dimensões: 2


Agora, para criar um tensor, precisamos aumentar a dimensão mais uma vez para ter um tensor de grau 3.

In [13]:
tensor = tf.constant([[[1, 2, 4],
                       [2, 5, 7]], 
                       [[4, 1, 6],
                       [6, 8, 8]],
                       [[4, 6, 1],
                        [6, 2, 1]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 4],
        [2, 5, 7]],

       [[4, 1, 6],
        [6, 8, 8]],

       [[4, 6, 1],
        [6, 2, 1]]])>

Preste atenção ao _shape_, temos 3 matrizes, de 2 linhas e 3 colunas cada. Vamos checar as dimensões.

In [14]:
print(f'Número de dimensões: {tensor.ndim}')

Número de dimensões: 3


Foi criado portanto um tensor de grau 3. Assim, criamos diferentes tipos de tensores que variam em seu grau, ou dimensões:

- Escalar: tensor de grau zero;
- Vetor: tensor de grau 1 (e.g, Força);
- Matrix: tensor de grau 2 (e.g, Matriz de condutividade);
- Tensor: um arranjo numérico n-dimensional.

#### tf.Variable()

Diferentemente do `tf.constant()`, o `tf.Variable()` criar tensores cujos elementos podem mudar.

In [15]:
# Criando tensores constantes e variáveis
unchangeable_tensor = tf.constant([5, 1])
changeable_tensor = tf.Variable([5, 1])

unchangeable_tensor, changeable_tensor

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 1])>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 1])>)

In [16]:
# Alterando elementos do tensor variável
changeable_tensor[0].assign(6)

changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([6, 1])>

Note que foi alterado o primeiro elemento do tensor variável. Se tentarmos fazer o mesmo com o tensor constante, obviamente teríamos um erro, pois os elementos não podem mudar.

Raramente será preciso decidir entre usar o tensor constante ou o variável. Durante as aplicações, o próprio TensorFlow toma essa decisão por nós.

#### Tensores randômicos

Tensores randômicos são tensores de tamanho arbitrário que contém números gerados aleatoriamente. As redes neurais utilizam tensores randômics para inicializar os pesos dos parâmetros ao receber dados de input, sendo o primeiro passo para compreender os dados. Por exemplo, o processo de aprendizado da rede neural envolve tomar um arranjo n-dimensional de número e refiná-lo até que ele represente algum padrão (uma forma comprimida de representar os dados originais).

In [17]:
# Criando dois tensores aleatórios (porém iguais)
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = (3, 2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3, 2))

random_1, random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [18]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

Note que apesar de os números parecerem randômicos, eles não são realmente. Por termos definido uma _seed_ para o gerador de números aleatórios, e depois termos pedido para gerar os números aleatórios de acordo com uma distribuição qualquer (neste caso, a normal), a _seed_ garante a reproducibilidade dos dados. É como se pedíssemos números aleatórios, mas com um tempero específico, que é a _seed_. Assim, ambos os tensores contém a mesma _seed_ de geração, de modo que ao aplicar a mesma distribuição, eles serão iguais.

#### Embaralhando a ordem dos elementos no tensor

Qual a necessidade de embaralhar elementos em um tensor?

A ordem dos dados pode afetar a maneira como a rede neural aprende, de modo que ela começa a organizar seus pesos de acordo com o padrão que encontrou devido simplesmente ao ordenamento dos dados, não porque identificou características nos atributos que realmente diferenciam os objetos na realidade.

Vamos supor que temos um conjunto de dados que contém 10000 imagens de gatos seguidas por 5000 imagens de cachorros. Por causa das primeiras 10 mil imagens serem apenas de gatos, o algoritmo pode perceber a ordem e classificar de acordo com isso, ao invés de padrões subjacentes nos dados. Isso pode levar ao overfitting do modelo.

In [19]:
not_shuffled = tf.constant([[4, 3],
                            [1, 4],
                            [5, 7]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 3],
       [1, 4],
       [5, 7]])>

In [20]:
# Emabaralhando o tensor
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 3],
       [5, 7],
       [1, 4]])>

In [21]:
# Embaralhando com uma seed para geração
tf.random.set_seed(10) # seed global
seed_shuffle = tf.random.shuffle(not_shuffled, seed = 10) # seed operacional
seed_shuffle

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 3],
       [5, 7],
       [1, 4]])>

Note que no primeiro caso, em que apenas embaralhamos os elementos dos tensor, a cada atualização na célula temos uma nova ordem de elementos no tensor. No segundo caso, em que definimos uma _seed_ global e uma operacional, e as duas são iguais, os elementos são embaralhados, mas a _seed_ garante a reproducibilidade a cada atualização da célula.

#### Criando tensores de arrays NumPy

Vimos que é possível construir tensores constantes, que não permitem mudanças nos seus elementos, e tensores variáveis, que permitem a mudança dos seus elementos mediante uso do método `assign()`. Além disso, vimos a importância dos tensores randomizados para o uso em redes neurais e no aprendizado de máquina. A randomização é o primeiro processo que ocorre após o algoritmo receber os inputs, pois ele inicializa os pesos de forma aleatória para serem ajustados posteriormente. 

Outro ponto importante abordado foi o uso do embaralhamento (shuffle) dos tensores que contém os dados. Dependendo do conjunto de dados, podemos ter muitos exemplos consecutivos com o mesmo rótulo, de modo que o algoritmo percebe essa ordem nos dados e passa a classificar de acordo com ela, perdendo a capacidade de generalização e levando até ao overfitting. Para isso, o método `tf.random.shuffle()` embaralha os elementos de um tensor, forçando o algoritmo a buscar padrões mais representativos do objeto real.

Como cada atualização do código pode levar a um resultado diferente do embaralhamento, é comum utilizar as sementes (seed) para garantir a reproducibilidade da alearoriedade dos experimentos. Isto é, garantimos que o embaralhamento acontecerá de uma forma a cada atualização. Para isso, utiliza-se um seed global com `tf.random.set_seed(x)` juntamente com uma seed operacional no tensor, passada como parâmetro para `tf.random.shuffle(seed = x)`

Agora, iremos estudar maneiras de construir tensores a partir de arranjos Numpy.

In [22]:
# Tensor que contém todos os elementos iguais a um
tf.ones([4, 4])

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [23]:
# Tensor com todos os elementos iguais a zero
tf.zeros([4, 3])

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

A diferença entre os conjuntos numéricos feitos por NumPy e tensores do Tensorflow é que estes podem rodar na GPU, que é muito mais rápida para processamento. Vamos criar um array NumPy e construir um tensor a partir dele. 

In [24]:
array_A = np.arange(1, 25, dtype = 'int32')
array_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [25]:
A = tf.constant(array_A)
print(A)
print(type(A))

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [26]:
# Podemos manipular o formato (shape) do tensor a partir da construção com array Numpy
B = tf.constant(array_A, shape = (2, 4, 3))
B

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])>

Podemos manipular as dimensões dos tensores criados a partir dos arranjos Numpy. Porém, devemos nos atentar que o shape deve ser tal que a multiplicação das componentes da dimensão é igual ao número de elementos no arranjo.

#### Informações sobre os tensores

In [27]:
tf_rank_4 = tf.zeros(shape = [3, 2, 3, 2])
tf_rank_4

<tf.Tensor: shape=(3, 2, 3, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]], dtype=float32)>

In [28]:
print('Informações sobre o tensor:',
      f'\nShape: {tf_rank_4.shape}',
      f'\nNúmero de dimensões: {tf_rank_4.ndim}',
      f'\nTamanho: {tf.size(tf_rank_4)}', # size = 3 x 2 x 3 x 2
      f'\nTipos: {tf_rank_4.dtype}',
      f'\nElementos no eixo zero: {tf_rank_4.shape[0]}',
      f'\nElementos no último eixo: {tf_rank_4.shape[-1]}') 

Informações sobre o tensor: 
Shape: (3, 2, 3, 2) 
Número de dimensões: 4 
Tamanho: 36 
Tipos: <dtype: 'float32'> 
Elementos no eixo zero: 3 
Elementos no último eixo: 2


#### Indexando e expandindo tensores

In [29]:
# Primeiros dois elementos de cada dimensão
tf_rank_4[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [30]:
# Primeiro elemento de cada dimensão exceto a última
tf_rank_4[:1, :, :, :] # Primeiro conjunto de matrizes
tf_rank_4[:1, :1, :, :] # Dentro do primeiro conjunto de matrizes, pego a primeira matriz
tf_rank_4[:1, :1, :1, :] # Dentro da primeira matriz, pego a primeira linha
tf_rank_4[:1, :1, :1, :1] # Dentro da primeira linha, pego o primeiro elemento da primeira coluna

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

In [31]:
tf_rank_2 = tf.constant([[10, 7],
                         [3, 4]])
tf_rank_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

Podemos buscar o último elemento de alguma dimensão dos tensores utilizando a indexação [-1].

In [32]:
tf_rank_2[:, -1] # Todos os elementos da última coluna

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [33]:
tf_rank_2[-1, :] # Todos os elementos da última linha

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4])>

Podemos manipular as dimensões de um tensor expandindo-o ao longo de alguma dimensão.

In [34]:
tf_rank_3 = tf_rank_2[..., tf.newaxis]
tf_rank_3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [35]:
# Expandindo o tensor, adicionando uma nova dimensão
tf.expand_dims(tf_rank_2, axis = -1) # Mesma operação, com método diferente

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

#### Operações básicas com tensores

Se os dados estão armazenados no formato de tensor, encontrar padrões nos tensores envolve aplicar operações para manipulá-los.

In [36]:
# Adicionar valores ao tensor com o operador de adição
tensor_1 = tf.constant([[10, 7],
                        [3, 4]])

tensor_1 + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

Quando adicionamos valores da forma como fizemos acima, o tensor não é modificado em si. Para que o resultado da operação seja o novo tensor, é preciso associar à variável, e.g, _tensor_1 = tensor_1 + 10_.

Podemos utilizar as funções do Tensorflow para operações básicas. Os tensores manipulados com as funções próprias do Tensorflow são processadas mais rapidamente, o que pode economizar tempo durante projetos com muitas operações nos tensores.

In [37]:
# Adicionando os valores e modificando o tensor
tf.add(tensor_1, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [38]:
# Multiplicando o mesmo tensor
tf.multiply(tensor_1, 3)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 21],
       [ 9, 12]])>

#### Multiplicação de matrizes com tensores

Uma das operações mais comuns dentro do Tensorflow é a multiplicação matricial.

In [39]:
# Multiplicando tensores com a função do Tensorflow}
print(tensor_1, '\n')

tf.matmul(tensor_1, tensor_1)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32) 



<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [40]:
# Multiplicando tensores com a operação nativa do Python
tensor_1 @ tensor_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [41]:
# Criando um segundo tensor
tf.random.set_seed(10)
tensor_2 = tf.random.uniform(shape = (3, 2), minval = 1, maxval = 20, dtype = 'int32', seed = 10)
print(tensor_2, '\n')

'''
Multiplicando tensor_1 @ tensor_2 resulta em erro, pois as dimensões internas das matrizes não são iguais.
Para haver uma multiplicação de matrizes, o número de colunas da primeira matriz deve ser igual ao número
de linhas da segunda.
'''
 
tensor_3 = tf.random.uniform(shape = (2, 3), minval = 1, maxval = 20, dtype = 'int32', seed = 10)
print(tensor_3)

tf.Tensor(
[[13 15]
 [ 1  3]
 [13  5]], shape=(3, 2), dtype=int32) 

tf.Tensor(
[[ 3 18  9]
 [12  9  8]], shape=(2, 3), dtype=int32)


In [42]:
tensor_2 @ tensor_3

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[219, 369, 237],
       [ 39,  45,  33],
       [ 99, 279, 157]])>

Portanto, temos as seguintes regras para multiplicação de matrizes:

- Os tensores a serem multiplicados devem ter dimensões internas iguais, isto é, o número de colunas do primeiro deve ser igual ao número de linhas do segundo.
- O tensor resultante tem o formato das dimensões externas dos tensores que foram multiplicados - neste caso temos uma matriz 3x3.

#### Reshape e Transpose

Se tentamos multiplicar o tensor por ele mesmo, a menos que seja uma matriz quadrada, resultará num erro devido ao formato do tensor. Para manipular as dimensões de modo a coincidir as colunas do primeiro com as linhas do segundo, usamos a função `reshape`.

In [43]:
print(tf.reshape(tensor_2, shape = [2, 3]),'\n')

tensor_2 @ tf.reshape(tensor_2, shape = [2, 3])

tf.Tensor(
[[13 15  1]
 [ 3 13  5]], shape=(2, 3), dtype=int32) 



<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[214, 390,  88],
       [ 22,  54,  16],
       [184, 260,  38]])>

A função reshape embaralha os valores de modo que eles fiquem no formato que você quer. Outro método usado para mudar o formato das matrizes é o `Transpose`. Nesta função, a diferença é que os eixos são transpostos, ao invés do formato ser construído a partir do embaralhamento dos valores.

In [44]:
tf.transpose(tensor_2), tf.reshape(tensor_2, shape = [2, 3])

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[13,  1, 13],
        [15,  3,  5]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[13, 15,  1],
        [ 3, 13,  5]])>)

In [45]:
tf.matmul(tf.transpose(tensor_2), tf.reshape(tensor_3, shape = [3, 2]))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[165, 350],
       [117, 346]])>

In [46]:
tensor_2, tensor_3

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[13, 15],
        [ 1,  3],
        [13,  5]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 3, 18,  9],
        [12,  9,  8]])>)

In [47]:
print('Tensor 2 Normal:',
      f'\n{tensor_2}', 
      '\n')

print('Tensor 2 Reshape:',
      f'\n{tf.reshape(tensor_2, shape = [2, 3])}', 
      '\n')

print('Tensor 2 Transposto:',
      f'\n{tf.transpose(tensor_2)}', 
      '\n')

Tensor 2 Normal: 
[[13 15]
 [ 1  3]
 [13  5]] 

Tensor 2 Reshape: 
[[13 15  1]
 [ 3 13  5]] 

Tensor 2 Transposto: 
[[13  1 13]
 [15  3  5]] 



#### Mudando o tipo dos dados do tensor

Os tipos dos dados em um tensor ocupam um espaço determinado de armazenamento e, dependendo do tipo específico dos dados, a precisão pode ser maior ou menor. Logicamente, dados com precisões maiores, i.e, mais casas decimais, tendem a ocupar maior espaço na memória além de requerer maior poder de processamento. 

Por isso, é importante conhecer os tipos de dados e como eles interagem com as unidades de processamento do Tensorflow. Por exemplo, o _float32_ ou _int32_ são tipos de dados que ocupam 32 bits de processamento na GPU. Para situações em que os dados não precisam de tamanha precisão, é importante modificá-los para tipos que ocupam menos espaço, de modo que o processamento passe a ser mais eficiente na hora do treinamento de longas listas de dados em formas de tensores.

In [48]:
# Criar um tensor com o tipo de dados float32
B = tf.constant([1.7, 3.1])
C = tf.constant([4, 1])
B.dtype, C.dtype

(tf.float32, tf.int32)

Por padrão, o Tensorflow utiliza do _int32_ ou _float32_ para armazenamento dos dados.

Para mudar o tipo, utilizamos o método `tf.cast()` especificando no argumento _dtype_ qual o tipo que queremos. Neste caso, estamos convertendo o _float_ de 32 para 16 bits de armazenamento, o que num contexto de milhões de dados, resultaria num ganho de performance grande.

In [49]:
# Mudar o tipo dos dados de float32 para float16 (redução de precisão)
D = tf.cast(B, dtype = tf.float16) # Casts a tensor to a new type.
D, B.dtype, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 3.1], dtype=float16)>,
 tf.float32,
 tf.float16)

#### Agregação de tensores

A prática de agregar tensores consiste em condensar múltiplos valores para um conjunto menor de valores significativos, que refletem o comportamento global dos dados.

In [60]:
# Valores absolutos (módulo)
E = tf.constant([-3, -7])
print('Tensor original:', E)
print('Valor absoluto:', tf.abs(E))

Tensor original: tf.Tensor([-3 -7], shape=(2,), dtype=int32)
Valor absoluto: tf.Tensor([3 7], shape=(2,), dtype=int32)


Forma de agregar valores em tensores:

- Valor máximo
- Valor mínimo 
- Média do tensor
- Soma do tensor

Vamos criar um tensor aleatório e aplicar as funções agregadoras.

In [64]:
tf.random.set_seed(20)
agg_tensor = tf.random.uniform(shape = [2, 4, 5], minval = 0, maxval = 50, seed = 20, dtype = tf.int32)
agg_tensor

<tf.Tensor: shape=(2, 4, 5), dtype=int32, numpy=
array([[[11, 28,  9, 42, 17],
        [29, 32, 20,  2, 40],
        [21,  9, 28,  4, 24],
        [44, 12, 22, 29, 26]],

       [[16, 27, 41, 15, 19],
        [29,  3, 38,  8,  1],
        [ 0, 24, 45, 38, 37],
        [42, 29, 17, 24, 43]]])>

In [71]:
# Valor máximo
'''
Computes tf.math.maximum of elements across dimensions of a tensor.
'''
max_val = tf.reduce_max(agg_tensor)

# Valor mínimo
'''
Computes the tf.math.minimum of elements across dimensions of a tensor.
'''
min_val = tf.reduce_min(agg_tensor)

# Média
'''
Computes the mean of elements across dimensions of a tensor.
'''
mean_val = tf.reduce_mean(agg_tensor, )

# Soma
'''
Computes the sum of elements across dimensions of a tensor.
'''
sum_val = tf.reduce_sum(agg_tensor)

max_val, min_val, mean_val, sum_val

(<tf.Tensor: shape=(), dtype=int32, numpy=45>,
 <tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=23>,
 <tf.Tensor: shape=(), dtype=int32, numpy=945>)

In [82]:
# Variações no axis
tf.reduce_sum(agg_tensor, axis = 0), tf.reduce_sum(agg_tensor, axis = 1), tf.reduce_sum(agg_tensor, axis = 2)

(<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
 array([[27, 55, 50, 57, 36],
        [58, 35, 58, 10, 41],
        [21, 33, 73, 42, 61],
        [86, 41, 39, 53, 69]])>,
 <tf.Tensor: shape=(2, 5), dtype=int32, numpy=
 array([[105,  81,  79,  77, 107],
        [ 87,  83, 141,  85, 100]])>,
 <tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[107, 123,  86, 133],
        [118,  79, 144, 155]])>)

Note o seguinte:
- Soma no axis = 0 é a soma elemento por elemento de cada dimensão
- Soma no axis = 1 é a soma dos elementos de cada coluna
- Soma no axis = 2 é a soma dos elementos em cada linha