# Seção 2 - Deep Learning and Tensorflow Fundamentals

### Definições

- **Deep Learning**: é uma sub-área de Machine Learning que envolve o aprendizado profundo de máquina, em que algoritmos buscam padrões em fontes de dados desestruturados, como textos, imagens, áudios. A modelagem acontece pelas redes neurais, que são estruturas que recebem, processam e constroem os modelos a partir dos dados, além de corrigir os erros e otimizar os parâmetros para aumentar a acurácia desses modelos. Assim, o Deep Learning atua como uma arquitetura de processamento e modelagem de dados não-estruturados, de forma automatizada a partir dos dados de input, resultando em previsões do objeto real em questão.

- **Redes Neurais**: As redes neurais são estruturas de processamento de dados que formam a arquitetura do Deep Learning. Como disse logo acima, elas buscam imitar o processo da cognição humana ao conectar diversas camadas de neurônios artificiais.Esses neurônios atuam combinando os dados recebidos, atribuindo-lhes pesos e vieses e associando-os a funções específicas de custo e ativação. Dessa forma, esses elementos trabalham juntos para definir as etapas de processamento até o output, que deve reconhecer, classificar ou descrever objetos reais a partir dos dados.

No Machine Learning, temos dados que são, na maioria das vezes, estruturados, e o procedimento de treinamento de um modelo com regras que encontramos ao manipular e processar os dados, além de haver um valor-alvo para basearmos a resposta do modelo em cada exemplo. No Deep Learning, temos apenas um input e um output esperado, e deixamos que as redes neurais processem os dados, encontrem alguma forma de estruturá-los e busquem por padrões que possam ajudar a chegar no resultado do output que esperamos.

Para um problema complexo, como ensinar um carro a dirigir sozinho, que possui um volume muito grande de dados, o Deep Learning pode ser a alternativa mais viável. Uma vez que estamos lidando com dados desestruturados e em grande volume, a estrutura de redes neurais traz uma capacidade de lidar de maneira mais eficiente com uma variedade de parâmetros e filtrá-los de acordo com sua relevância em cada camada.

**O Deep Learning é indicado para as seguintes situações:**

- Problemas com longas listas de regras
- Ambientes que mudam constantemente, i.e, Adaptação a novos cenários
- Descobrir insights em grandes quantidades de dados

**Deep Learning não é indicado nas seguintes situações:**

- Quando necessitamos interpretabilidade: os padrões de DL normalme}nte não são interpretáveis por humanos
- Quando a abordagem tradicional é melhor, isto é, com um sistema de regras simples
- Quando erros são inaceitáveis, pois outputs no DL podem ser imprevisíveis 
- Quando não há muitos dados disponíveis, pois modelos de DL necessitam de grandes quantidade de dados para manter uma boa performance


### Tensorflow

Tensorflow é uma biblioteca de Machine Learning end-to-end. Nela, é possível escrever códigos de DL em Python e rodá-los utilizando GPU (Graphics Processing Units) ou TPU (Tensor Processing Units). O Tensorflow permite o pré-processamento dos dados, modelagem e deploy de aplicações, além de oferecer um hub de modelos já construídos de DL.

In [2]:
import tensorflow as tf

In [4]:
print(f'Versão do Tensorflow: {tf.__version__}')

Versão do Tensorflow: 2.15.0


#### tf.constant()

In [7]:
# Criar tensores com tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

Criamos um tensor constante de ordem zero, ou seja, um escalar. O escalar é simplesmente a representação de um número. Se checarmos o número de dimensões desse tensor escalar, resultará em:

In [8]:
print(f'Número de dimensões: {scalar.ndim}')

Número de dimensões: 0


In [9]:
vector = tf.constant([7, 2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 2])>

Note que, para criar um vetor, passamos uma lista de números para a função `tf.constant()`. Vamos checar as dimensões do vetor:

In [10]:
print(f'Número de dimensões: {vector.ndim}')

Número de dimensões: 1


Como era de se esperar, o vetor já é um tensor de grau 1, contendo portanto uma dimensão. Se aumentarmos a dimensão, teremos uma matriz.

In [11]:
matrix = tf.constant([[5, 2],
                     [3, 6]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 2],
       [3, 6]])>

In [12]:
print(f'Número de dimensões: {matrix.ndim}')

Número de dimensões: 2


In [13]:
# Especificando o tipo dos dados no tensor
matrix_2 = tf.constant([[3., 5., 1.],
                        [5., 12., 43.],
                        [2., 5., 8.]], dtype = tf.float16)
matrix_2

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[ 3.,  5.,  1.],
       [ 5., 12., 43.],
       [ 2.,  5.,  8.]], dtype=float16)>

Manipular os tipos dos dados é útil, pois pode economizar espaço de armazenamento das variáveis nas unidades de processamento, tornando os processos mais rápidos. Para número que não carregam tanta precisão, podemos utilizar um tipo de dados que ocupa menos espaço.

Note que essa matriz possui um formato diferente da primeira, contudo o número de dimensões continua o mesmo.

In [14]:
print(f'Número de dimensões: {matrix_2.ndim}')

Número de dimensões: 2


Agora, para criar um tensor, precisamos aumentar a dimensão mais uma vez para ter um tensor de grau 3.

In [16]:
tensor = tf.constant([[[1, 2, 4],
                       [2, 5, 7]], 
                       [[4, 1, 6],
                       [6, 8, 8]],
                       [[4, 6, 1],
                        [6, 2, 1]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 4],
        [2, 5, 7]],

       [[4, 1, 6],
        [6, 8, 8]],

       [[4, 6, 1],
        [6, 2, 1]]])>

Preste atenção ao _shape_, temos 3 matrizes, de 2 linhas e 3 colunas cada. Vamos checar as dimensões.

In [17]:
print(f'Número de dimensões: {tensor.ndim}')

Número de dimensões: 3


Foi criado portanto um tensor de grau 3. Assim, criamos diferentes tipos de tensores que variam em seu grau, ou dimensões:

- Escalar: tensor de grau zero;
- Vetor: tensor de grau 1 (e.g, Força);
- Matrix: tensor de grau 2 (e.g, Matriz de condutividade);
- Tensor: um arranjo numérico n-dimensional.

#### tf.Variable()

Diferentemente do `tf.constant()`, o `tf.Variable()` criar tensores cujos elementos podem mudar.

In [21]:
# Criando tensores constantes e variáveis
unchangeable_tensor = tf.constant([5, 1])
changeable_tensor = tf.Variable([5, 1])

unchangeable_tensor, changeable_tensor

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 1])>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 1])>)

In [22]:
# Alterando elementos do tensor variável
changeable_tensor[0].assign(6)

changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([6, 1])>

Note que foi alterado o primeiro elemento do tensor variável. Se tentarmos fazer o mesmo com o tensor constante, obviamente teríamos um erro, pois os elementos não podem mudar.

Raramente será preciso decidir entre usar o tensor constante ou o variável. Durante as aplicações, o próprio TensorFlow toma essa decisão por nós.

#### Tensores randômicos

Tensores randômicos são tensores de tamanho arbitrário que contém números gerados aleatoriamente. As redes neurais utilizam tensores randômics para inicializar os pesos dos parâmetros ao receber dados de input, sendo o primeiro passo para compreender os dados. Por exemplo, o processo de aprendizado da rede neural envolve tomar um arranjo n-dimensional de número e refiná-lo até que ele represente algum padrão (uma forma comprimida de representar os dados originais).

In [40]:
# Criando dois tensores aleatórios (porém iguais)
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = (3, 2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3, 2))

random_1, random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [41]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

Note que apesar de os números parecerem randômicos, eles não são realmente. Por termos definido uma _seed_ para o gerador de números aleatórios, e depois termos pedido para gerar os números aleatórios de acordo com uma distribuição qualquer (neste caso, a normal), a _seed_ garante a reproducibilidade dos dados. É como se pedíssemos números aleatórios, mas com um tempero específico, que é a _seed_. Assim, ambos os tensores contém a mesma _seed_ de geração, de modo que ao aplicar a mesma distribuição, eles serão iguais.

#### Embaralhando a ordem dos elementos no tensor

Qual a necessidade de embaralhar elementos em um tensor?

A ordem dos dados pode afetar a maneira como a rede neural aprende, de modo que ela começa a organizar seus pesos de acordo com o padrão que encontrou devido simplesmente ao ordenamento dos dados, não porque identificou características nos atributos que realmente diferenciam os objetos na realidade.

Vamos supor que temos um conjunto de dados que contém 10000 imagens de gatos seguidas por 5000 imagens de cachorros. Por causa das primeiras 10 mil imagens serem apenas de gatos, o algoritmo pode perceber a ordem e classificar de acordo com isso, ao invés de padrões subjacentes nos dados. Isso pode levar ao overfitting do modelo.

In [47]:
not_shuffled = tf.constant([[4, 3],
                            [1, 4],
                            [5, 7]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 3],
       [1, 4],
       [5, 7]])>

In [62]:
# Emabaralhando o tensor
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 3],
       [5, 7],
       [1, 4]])>

In [56]:
# Embaralhando com uma seed para geração
tf.random.set_seed(10) # seed global
seed_shuffle = tf.random.shuffle(not_shuffled, seed = 10) # seed operacional
seed_shuffle

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 3],
       [5, 7],
       [1, 4]])>

Note que no primeiro caso, em que apenas embaralhamos os elementos dos tensor, a cada atualização na célula temos uma nova ordem de elementos no tensor. No segundo caso, em que definimos uma _seed_ global e uma operacional, e as duas são iguais, os elementos são embaralhados, mas a _seed_ garante a reproducibilidade a cada atualização da célula.

#### Criando tensores de arrays NumPy